### ISSUE TITLE
CollisionServiceProvider::register() should not try to instantiate ExceptionHandler

### ISSUE THREAD

**Issue by AegirLeet** [nunomaduro/collision#141]
https://github.com/nunomaduro/collision/blob/834a201a4866a70a06eeef29730c7ba1c9da4b2e/src/Adapters/Laravel/CollisionServiceProvider.php#L63

If the application's implementation of `ExceptionHandler` has dependencies (in its constructor) provided by another Service Provider, instantiation of `ExceptionHandler` may fail (depending on Service Provider load order). It's generally a very bad idea to do anything other than registering container bindings in a Provider's `register()` method. From the [docs](https://laravel.com/docs/7.x/providers#writing-service-providers):

> Within the register method, you should **only bind things into the service container**. You should never attempt to register any event listeners, routes, or any other piece of functionality within the register method.

> As mentioned previously, within the register method, you should only bind things into the service container. You should never attempt to register any event listeners, routes, or any other piece of functionality within the register method. Otherwise, you may accidentally use a service that is provided by a service provider which has not loaded yet.

**Comment by nunomaduro** [comment]
Can you make a pull request to fix this?

**Comment by AegirLeet** [comment]
Sure, I'll submit a PR.

**Comment by Levivb** [comment]
I second this.

Currently in the process of upgrading a multi modulair application to Laravel 6 (and 7) (long overdue, I know)

In Laravel 6 a lot of Service Providers received the `DeferrableProvider` interface. Along with the `MailServiceProvider`, causing the 'mailer' class to be unavailable during boot. The `services` file containing the mapping from `provides` to `service provider` is read/created after registering all classes.

In our case our Exception Handler needs the Mailer class, which is injected via DI. The exception handler is already created during the booting process because of this package.

The provided PR should work (from the looks of it) and it's an even nicer solution due to usage of the decorator pattern.

A monkeypatch successfully I tried myself is:
```diff
-           $appExceptionHandler = $this->app->make(ExceptionHandlerContract::class);

            $this->app->singleton(
                ExceptionHandlerContract::class,
                function ($app) {
+                  $appExceptionHandler = $this->app->make(ExceptionHandlerContract::class);
+
                    return new ExceptionHandler($app, $appExceptionHandler);
                }
            );
```

For now I'll rebind the ExceptionHandler in the `AppServiceProvider::boot` which should work just as well for now

**Comment by cyreb7** [comment]
In Laravel, running `php artisan config:cache` with Collision installed in the project, then running tests causes our Mockery mocked exception handlers to falsely report no exception was thrown and fail our tests. Monkey patching https://github.com/nunomaduro/collision/pull/142 fixes the issue.

**Comment by nunomaduro** [comment]
No plans to change this.
