### ISSUE TITLE
collision slows down the unit testrun by a factor of 2-3x

### ISSUE THREAD

**Issue by staabm** [nunomaduro/collision#160]
we [integrated](https://github.com/redaxo/redaxo/pull/3910) collision into https://github.com/redaxo/redaxo

running the testsuite is now 2-3x slower then without collision.
is this a known problem?

tested on a linux VM with collision

```
time vendor/bin/phpunit
.
.
real    0m18,758s
user    0m1,947s
sys     0m0,257s
```

without collision (just deleted the `printerClass="NunoMaduro\Collision\Adapters\Phpunit\Printer"` line from phpunix.xml)

```
time vendor/bin/phpunit
.
.
real    0m8,769s
user    0m1,753s
sys     0m0,275s
```

on my windows desktop its even slower

**Comment by owenvoke** [comment]
Yeah, this is a known problem. It's due to the use of `usleep()` (https://github.com/nunomaduro/collision/issues/121). This would be nice to be able to disable it either with a configuration option, or just by default. 🤷🏻

It does look quite a bit worse without the sleep as the test suite just jumps... but at the same time, running the Pest test suite (only 223 tests) jumps from 6 to 0.67 seconds. For really large test suites, I can imagine that this difference would be huge. 👍🏻 (https://asciinema.org/a/4j58r9VRsMcD5QRMDaLjJOObT)

**Comment by JoelLarson** [comment]
I ran into this when upgrading an application with a few hundred unit tests. To help others in the meantime since this is a requirement on Laravel 8 to get the test artisan command, I have this workaround:

AppServiceProvider.php
```
<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use NunoMaduro\Collision\Adapters\Laravel\Commands\TestCommand;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        $this->app->bind(TestCommand::class, function () {
            return new class extends TestCommand {
                protected $arguments = [];
            };
        });
    }

    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        //
    }
}
```

This will disable the collision PHPUnit printer and use the one built into PHPUnit. It's not ideal but it saves quite a bit of time while the fix is being worked on.

**Comment by staabm** [comment]
We also reverted to the phpunit default printer because of the performance penalty

**Comment by nunomaduro** [comment]
@owenvoke We need to address this before PEST v1.0.

**Comment by owenvoke** [comment]
@nunomaduro, I'm not entirely sure how we address this issue. Either we remove the `usleep()` completely (making it jumpy), reduce the `usleep()` (still kind of jumpy), or have an option to disable it. I feel like disabling the `usleep()` by default and maybe having a static variable that can be configured would be good? 🤔 E.g.

```php
// In the Style class
public static $enableSmoothLoading = false;

// In another file (e.g. in Pest)
\NunoMaduro\Collision\Adapters\Phpunit\Style::$enableSmoothLoading = true;
```

<details>
<summary>Example diff of implementation</summary>

```diff
diff --git a/src/Adapters/Phpunit/Style.php b/src/Adapters/Phpunit/Style.php
index f61fb88..b8c1e57 100644
--- a/src/Adapters/Phpunit/Style.php
+++ b/src/Adapters/Phpunit/Style.php
@@ -24,6 +24,9 @@ final class Style
      */
     private $output;
 
+    /** @var bool */
+    public static $enableSmoothLoading = false;
+
     /**
      * Style constructor.
      */
@@ -69,7 +72,10 @@ final class Style
         }
 
         $state->eachTestCaseTests(function (TestResult $testResult) {
-            usleep(20000);
+            if (self::$enableSmoothLoading) {
+                usleep(20000);
+            }
+
             $this->output->writeln($this->testLineFrom(
                 $testResult->color,
                 $testResult->icon,

```

</details>

**Comment by nunomaduro** [comment]
Fixed.
